try {
  hello();
} catch (err) {
  console.log(err);
}

try {
  nice();
} catch {
  console.log('Test Error');
}
